name: Coding Standards

on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  # Runs PHP coding standards checks.
  #
  # Violations are reported inline with annotations.
  #
  # Performs the following steps:
  # - Checks out the repository.
  # - Sets up PHP.
  # - Logs debug information.
  # - Logs PHP_CodeSniffer debug information.
  # - Runs PHPCS on the full codebase with warnings suppressed.
  phpcs:
    name: PHP coding standards
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'ClassicPress/ClassicPress-v2' || github.event_name == 'pull_request' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
          coverage: none
          tools: cs2pr

      - name: Log debug information
        run: |
          php --version
          composer --version

      - name: Log PHPCS debug information
        run: phpcs -i

      - name: Run PHPCS on all Core files
        run: phpcs --runtime-set text_domain doit --standard=cpcs.xml -q -n --report=checkstyle | cs2pr
