name: ClassicPress Directory Coding Standard checks.

on: [pull_request, push]

jobs:
  phpcs:
      name: WPCS
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4
        - name: WPCS check
          uses: 10up/wpcs-action@stable
        - name: spy
          run: |
            ls
            cat composer.json
          if: always()
          
