name: ClassicPress Directory Coding Standard checks.

on: [pull_request, push]

jobs:
  phpcs:
      name: CPCS
      runs-on: ubuntu-latest
      steps:
        - name: Cancel previous runs of this workflow (pull requests only)
          if: ${{ github.event_name == 'pull_request' }}
          uses: styfle/cancel-workflow-action@0.12.1
          with:
            access_token: ${{ github.token }}
        - uses: actions/checkout@v4
        - name: CPCS get rules
          run: |
            wget https://raw.githubusercontent.com/ClassicPress/ClassicPress-Coding-Standards/main/phpcs.xml
            sed -i '/^\t<!-- start config -->.*/a\
              <file>.</file>
              ' phpcs.xml
            sed -i '/MY_DOMAIN/ s//do-it-bad/' phpcs.xml
            mv phpcs.xml phpcs.xml.dist
        - name: CPCS checks
          uses: 10up/wpcs-action@stable
          with:
            use_local_config: 'true'
            enable_warnings: 'true'
            extra_args: '--report-json=./phpcs.json'
        - name: Update summary
          run: |
            npm i -g github:10up/phpcs-json-to-md
            phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
            cat phpcs.md >> $GITHUB_STEP_SUMMARY
          if: always()
