name: Generate Installable Plugin, and Upload as Release Asset
on:
  release:
    types: [published]
jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create artifact
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -X -O ${{ github.workspace }}/.${{  github.ref_name }}.zip -r ${{ github.workspace }}.zip ${{ github.event.repository.name }}  -x *.git* 
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
            name: ${{ github.event.repository.name }}
            path: ${{ github.event.repository.name }}.${{  github.ref_name }}.zip
      - name: Upload to release
        uses: JasonEtco/upload-to-release@master
        with:
          args: ${{ github.event.repository.name }}.${{  github.ref_name }}.zip application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
