name: PHP Syntax Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  test-php:
    name: "PHP ${{ matrix.php }} on MySQL ${{matrix.mysql}}${{ matrix.memcached && ' with memcached' || '' }}${{ 'xdebug' == matrix.coverage && ' with XDebug' || '' }}${{ matrix.experimental && ' - Experimental' || '' }}"
    runs-on: ubuntu-latest
    
    steps:
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
      - name: Check syntax
        uses: mlocati/check-php-syntax@v1
        with:
          directory: .
          fail-on-warnings: true
