name: PHP Syntax Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  test-php:
    name: "PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [ '8.4', '8.3', '8.2', '8.1', '8.0', '7.4' ]    
    steps:
      - name: Cancel previous runs of this workflow (pull requests only)
        if: ${{ github.event_name == 'pull_request' }}
        uses: styfle/cancel-workflow-action@0.12.1
        with:
          access_token: ${{ github.token }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
          extensions: opcache
      - name: Check syntax
        uses: mlocati/check-php-syntax@v1
        with:
          directory: .
          fail-on-warnings: true
