name: PHP Syntax Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:

jobs:
  test-php:
    name: "PHP ${{ matrix.php }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [ '8.4', '8.3', '8.2', '8.1', '8.0', '7.4' ]    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "${{ matrix.php }}"
      - name: Check syntax
        uses: mlocati/check-php-syntax@v1
        with:
          directory: .
          fail-on-warnings: true
