name: Test.

on: [pull_request, push]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
      name: TEST
      runs-on: ubuntu-latest
      steps:

        - name: Test variable
          run: |
              echo Hi ${{ github.actor }}! 👋
